# Collatz Sequence:
# Implement a program that takes a starting number and generates 
# the Collatz sequence until it reaches 1. The Collatz sequence is 
# generated by the following rules: if the current number is even,
# divide it by 2; if it's odd, multiply it by 3 and add 1.

#COLLATZ Game:
num=int(input("Enter a number:"))

while(num>1):
    if num%2==0:
        num=num/2
    
    else:
        num=num*3
        num+=1
    print(num)
    num=-1  
